language: dart

git:
  depth: 3
  submodules: false

# safelist 
branches:
  only:
    - master
    - development

jobs:
  # if any build fails, finish job
  fast_finish: true
  include:
    - name: "Flutter Test"
      os: linux
      dist: trusty
      language: bash
      script:
        - ./flutter/bin/flutter test --coverage


before_script:
  - git clone https://github.com/flutter/flutter.git;
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/shared/.pub-cache