<<<<<<< refs/remotes/origin/master
language: dart

git:
  depth: 3
  submodules: false

# safelist 
branches:
  only:
    - master
    - development

jobs:
  # if any build fails, finish job
  fast_finish: true
  include:
    - name: "Flutter Test"
      os: linux
      dist: trusty
      language: bash
      script:
        - ./flutter/bin/flutter test --coverage


before_script:
  - git clone https://github.com/flutter/flutter.git;
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - $HOME/shared/.pub-cache
=======
os:
  - linux
sudo: true
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
cache:
  directories:
    - $HOME/.pub-cache
>>>>>>> added travis.yml file (#50)
