language: dart

git:
  depth: 3
  submodules: false

# safelist 
branches:
  only:
    - master
    - development

jobs:
  include:
    - name: "Android appbundle"
      os: linux
      language: android
      android:
        components:
            # use the latest revision of Android SDK Tools
            # - tools
            # - platform-tools
        
          # The BuildTools version used by your project
          - build-tools-28.0.3

          # The SDK version used to compile your project
          - android-26

          # Specify at least one system image,
          # if you need to run emulator(s) during your tests
          # - sys-img-x86-android-26
          # - sys-img-armeabi-v7a-android-17

      # Prefer appbundle over apk    
      script:
        - ./flutter/bin/flutter build appbundle

    - name: "iOS release build"
      os: osx
      # Travis CI uses macOS 10.13 (and Xcode 9.4.1) by default. 
      osx_image: xcode11.3
      language: objective-c
      script:
        # defaults to release build
        - ./flutter/bin/flutter build ios --no-codesign   

    - name: "Flutter Test"
      os: linux
      dist: trusty
      language: bash
      script:
        - ./flutter/bin/flutter test --coverage


before_script:
  # try to avoid downloading flutter
  - if [ ! -f $HOME/flutter/bin/flutter ] ; then git clone https://github.com/flutter/flutter.git -b beta ; fi
  - ./flutter/bin/flutter doctor

cache:
  directories:
    - flutter
    - $HOME/shared/.pub-cache