// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'coordinate.dart';

// **************************************************************************
// BeanGenerator
// **************************************************************************

/*
Exception while parsing field: _floor!
Exception: Only one Column annotation is allowed on a Field!
#0      ParsedBean._makeField (package:jaguar_orm_gen/src/parser/parser.dart:360:7)
#1      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:328:21)
#2      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#3      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:56)
#4      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
#5      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#6      _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
#7      _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#8      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#9      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#10     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#11     Future.wait (dart:async/future.dart:393:26)
#12     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#13     _rootRun (dart:async/zone.dart:1126:13)
#14     _CustomZone.run (dart:async/zone.dart:1023:19)
#15     _runZoned (dart:async/zone.dart:1518:10)
#16     runZoned (dart:async/zone.dart:1502:12)
#17     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#18     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#19     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:486:19)
#20     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#21     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:484:23)
<asynchronous suspension>
#22     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#23     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#24     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:441:22)
#25     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#26     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:437:17)
#27     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:375:38)
#28     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#29     Future.wait (dart:async/future.dart:393:26)
#30     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:374:36)
#31     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#32     _rootRunUnary (dart:async/zone.dart:1134:38)
#33     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#34     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#35     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#36     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#37     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#38     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#39     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#40     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#41     _rootRunUnary (dart:async/zone.dart:1134:38)
#42     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#43     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#44     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#45     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#46     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#47     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#48     _rootRunUnary (dart:async/zone.dart:1134:38)
#49     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#50     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#51     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#52     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#53     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#54     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#55     _rootRun (dart:async/zone.dart:1126:13)
#56     _CustomZone.run (dart:async/zone.dart:1023:19)
#57     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#58     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


#0      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:347:9)
#1      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#2      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:56)
#3      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
#4      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#5      _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
#6      _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#7      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#10     Future.wait (dart:async/future.dart:393:26)
#11     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#17     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#18     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:486:19)
#19     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#20     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:484:23)
<asynchronous suspension>
#21     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#22     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#23     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:441:22)
#24     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#25     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:437:17)
#26     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:375:38)
#27     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#28     Future.wait (dart:async/future.dart:393:26)
#29     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:374:36)
#30     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#39     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#45     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#46     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#47     _rootRunUnary (dart:async/zone.dart:1134:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#52     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#53     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#54     _rootRun (dart:async/zone.dart:1126:13)
#55     _CustomZone.run (dart:async/zone.dart:1023:19)
#56     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#57     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

*/
