// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'floor.dart';

// **************************************************************************
// BeanGenerator
// **************************************************************************

/*
Exception while parsing field: _polygons!
Exception while parsing field: _floor!
Exception: Only one Column annotation is allowed on a Field!
#0      ParsedBean._makeField (package:jaguar_orm_gen/src/parser/parser.dart:360:7)
#1      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:328:21)
#2      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#3      ParsedBean.parseRelation (package:jaguar_orm_gen/src/parser/parser.dart:387:60)
#4      ParsedBean._relation (package:jaguar_orm_gen/src/parser/parser.dart:371:5)
#5      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:334:16)
#6      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#7      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:56)
#8      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
#9      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#10     _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
#11     _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#12     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#13     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#14     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#15     Future.wait (dart:async/future.dart:393:26)
#16     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#17     _rootRun (dart:async/zone.dart:1126:13)
#18     _CustomZone.run (dart:async/zone.dart:1023:19)
#19     _runZoned (dart:async/zone.dart:1518:10)
#20     runZoned (dart:async/zone.dart:1502:12)
#21     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#22     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#23     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:486:19)
#24     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#25     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:484:23)
<asynchronous suspension>
#26     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#27     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#28     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:441:22)
#29     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#30     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:437:17)
#31     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:375:38)
#32     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#33     Future.wait (dart:async/future.dart:393:26)
#34     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:374:36)
#35     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#36     _rootRunUnary (dart:async/zone.dart:1134:38)
#37     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#38     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#39     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#40     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#41     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#42     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#43     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#44     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#45     _rootRunUnary (dart:async/zone.dart:1134:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#51     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#52     _rootRunUnary (dart:async/zone.dart:1134:38)
#53     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#54     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#55     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#56     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#57     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#58     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#59     _rootRun (dart:async/zone.dart:1126:13)
#60     _CustomZone.run (dart:async/zone.dart:1023:19)
#61     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#62     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#63     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#64     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#65     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#66     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


#0      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:347:9)
#1      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#2      ParsedBean.parseRelation (package:jaguar_orm_gen/src/parser/parser.dart:387:60)
#3      ParsedBean._relation (package:jaguar_orm_gen/src/parser/parser.dart:371:5)
#4      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:334:16)
#5      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#6      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:56)
#7      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
#8      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#9      _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
#10     _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#11     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#13     ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#14     Future.wait (dart:async/future.dart:393:26)
#15     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#16     _rootRun (dart:async/zone.dart:1126:13)
#17     _CustomZone.run (dart:async/zone.dart:1023:19)
#18     _runZoned (dart:async/zone.dart:1518:10)
#19     runZoned (dart:async/zone.dart:1502:12)
#20     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#21     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#22     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:486:19)
#23     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#24     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:484:23)
<asynchronous suspension>
#25     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#26     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#27     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:441:22)
#28     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#29     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:437:17)
#30     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:375:38)
#31     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#32     Future.wait (dart:async/future.dart:393:26)
#33     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:374:36)
#34     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#35     _rootRunUnary (dart:async/zone.dart:1134:38)
#36     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#37     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#38     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#39     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#40     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#41     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#42     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#43     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#44     _rootRunUnary (dart:async/zone.dart:1134:38)
#45     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#46     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#47     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#48     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#49     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#50     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#51     _rootRunUnary (dart:async/zone.dart:1134:38)
#52     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#53     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#54     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#55     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#56     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#57     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#58     _rootRun (dart:async/zone.dart:1126:13)
#59     _CustomZone.run (dart:async/zone.dart:1023:19)
#60     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#61     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#64     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)


#0      ParsedBean._parseFields (package:jaguar_orm_gen/src/parser/parser.dart:347:9)
#1      ParsedBean.detect (package:jaguar_orm_gen/src/parser/parser.dart:75:5)
#2      BeanGenerator.generateForAnnotatedElement (package:jaguar_orm_gen/src/hook/hook.dart:38:56)
#3      GeneratorForAnnotation.generate (package:source_gen/src/generator_for_annotation.dart:47:30)
#4      _generate (package:source_gen/src/builder.dart:280:35)
<asynchronous suspension>
#5      _Builder._generateForLibrary (package:source_gen/src/builder.dart:73:15)
#6      _Builder.build (package:source_gen/src/builder.dart:67:11)
<asynchronous suspension>
#7      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#8      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:29)
#9      ListIterator.moveNext (dart:_internal/iterable.dart:346:26)
#10     Future.wait (dart:async/future.dart:393:26)
#11     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#12     _rootRun (dart:async/zone.dart:1126:13)
#13     _CustomZone.run (dart:async/zone.dart:1023:19)
#14     _runZoned (dart:async/zone.dart:1518:10)
#15     runZoned (dart:async/zone.dart:1502:12)
#16     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#17     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#18     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:486:19)
#19     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#20     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:484:23)
<asynchronous suspension>
#21     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#22     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#23     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:441:22)
#24     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#25     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:437:17)
#26     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:375:38)
#27     MappedIterator.moveNext (dart:_internal/iterable.dart:395:18)
#28     Future.wait (dart:async/future.dart:393:26)
#29     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:374:36)
#30     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:320:20)
#31     _rootRunUnary (dart:async/zone.dart:1134:38)
#32     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#33     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#34     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#35     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#36     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#37     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:34:15)
#38     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:293:13)
#39     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#40     _rootRunUnary (dart:async/zone.dart:1134:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#42     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#43     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#44     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#45     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#46     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#47     _rootRunUnary (dart:async/zone.dart:1134:38)
#48     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#49     _FutureListener.handleValue (dart:async/future_impl.dart:140:18)
#50     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682:45)
#51     Future._propagateToListeners (dart:async/future_impl.dart:711:32)
#52     Future._completeWithValue (dart:async/future_impl.dart:526:5)
#53     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556:7)
#54     _rootRun (dart:async/zone.dart:1126:13)
#55     _CustomZone.run (dart:async/zone.dart:1023:19)
#56     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#57     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#58     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#60     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#61     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

*/
